# Build an image with glibc and bash.
# This is the starting point of the other images. We don't have to keep recompiling it.

# Use the empty image with the portage tree as the first stage
FROM gentoo/portage:latest as portage

# Gentoo stage3 is the second stage, basically an unpacked Gentoo Linux
FROM gentoo/stage3:amd64-nomultilib-openrc as gentoo


# Copy the portage tree into gentoo.
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN mkdir -p /destination/usr/lib/gcc

#Our  build environment. Portage config here. Global to all our builds
COPY pre/etc /etc

## Any preexisting make.profile not a symlink will cause eselect to fail

#RUN eselect profile  list
RUN eselect profile  set 12

# shadow is here so that later packages that create users (acct-user) will have useradd
RUN ROOT=/destination emerge  --quiet sys-libs/glibc sys-apps/shadow app-shells/bash 

#Our  Library Config and default passwd file. Global to all our builds
COPY post-glibc/ /destination/

#Copy C++ runtimes. This removes the GCC version from the path
RUN find /usr/lib/gcc -type f -name "*.so*" -exec cp  {} /destination/usr/lib/gcc/ \;

# Clean up unneeded. 

RUN rm  -f /destination/usr/lib/gcc/*fortran*

CMD ["/bin/bash", "-c", "sleep 3600"]